# Generated by Django 4.2.7 on 2023-11-18 05:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_confirmed_user_email_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전공'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True, region=None, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='학번'),
        ),
    ]
