# Generated by Django 4.2.7 on 2023-11-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_major_user_phone_number_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, max_length=1, null=True, verbose_name='학년'),
        ),
    ]
