# Generated by Django 4.2.7 on 2023-11-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=40, null=True, verbose_name='전화번호'),
        ),
    ]
