# Generated by Django 4.2.6 on 2023-11-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
