# Generated by Django 4.2.6 on 2023-11-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_department_grade_repair_species_searchhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='filter',
            field=models.CharField(choices=[('IT', 'IT'), ('마케팅', '마케팅'), ('언어', '언어'), ('제작/글쓰기', '제작/글쓰기')], default='', max_length=10, null=True),
        ),
    ]
