# Generated by Django 4.2.6 on 2023-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_searchhistory_filter_product_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter',
            field=models.CharField(choices=[('it', 'it'), ('마케팅', '마케팅'), ('언어', '언어'), ('제작/글쓰기', '제작/글쓰기')], default='', max_length=10, null=True),
        ),
    ]
