# Generated by Django 4.2.6 on 2023-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_registrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='TeamNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '팀원수',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='framework',
            field=models.CharField(blank=True, max_length=50, verbose_name='FrameWork'),
        ),
        migrations.AddField(
            model_name='product',
            name='meet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categoy', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='team_number',
            field=models.ManyToManyField(blank=True, related_name='team', to='products.teamnumber'),
        ),
    ]
