# Generated by Django 4.2.6 on 2023-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_teamnumber_product_framework_product_meet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meet',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
