# Generated by Django 4.2.6 on 2023-11-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
